version: 2

workflows:
    version: 2
    pipeline:
        jobs:
            - test

jobs:
    test:
        environment:
            - MSBUILDDISABLENODEREUSE: 1
        working_directory: ~/project
        docker:
            - image: mcr.microsoft.com/dotnet/core/sdk
        steps:
            - checkout
            - run: dotnet test --configuration Release --logger:console;noprogress=true
