version: 2

workflows:
    version: 2
    pipeline:
        jobs:
            - test

jobs:
    test:
        environment:
            - DOTNET_CLI_TELEMETRY_OPTOUT: 1
        working_directory: ~/project
        docker:
            - image: mcr.microsoft.com/dotnet/core/sdk
        steps:
            - checkout
            - run: dotnet test --configuration Release --diag:log.txt
            - store_artifacts:
                path: log.txt
